name: unity build plugins

on: 
  workflow_dispatch:
    inputs:
      websocket:
        type: choice
        options:
        - "0"
        - "1"
        - "2"
        - "3"
        default: '1'
      config:
        type: choice
        description: Release Or Debug
        options:
        - "Release"
        - "Debug"
        default: 'Release'

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        shell: bash
        run: |
          cd ~
          rm -rf ~/android-ndk-r21b
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r23c-linux.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: BuildAndroid
        uses: ./.github/workflows/composites/unity-build-plugins/android/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}
          
  ohos:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        shell: bash
        run: |
          cd ~
          curl -O https://repo.huaweicloud.com/harmonyos/os/4.1-Release/ohos-sdk-windows_linux-public.tar.gz
          tar xvfz ohos-sdk-windows_linux-public.tar.gz
          cd ohos-sdk/linux
          unzip -q -o -d ./ native-linux-x64-4.1.7.5-Release.zip
      - name: BuildOHOS
        uses: ./.github/workflows/composites/unity-build-plugins/ohos/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}

  ios:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: BuildiOS
        uses: ./.github/workflows/composites/unity-build-plugins/ios/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}

  osx:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: BuildOSX
        uses: ./.github/workflows/composites/unity-build-plugins/osx/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}

  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: BuildWindows
        uses: ./.github/workflows/composites/unity-build-plugins/windows/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}

  linux64:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: BuildLinux
        uses: ./.github/workflows/composites/unity-build-plugins/linux/
        with:
          config: ${{ github.event.inputs.config }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: v8_9.4.146.24
          websocket: ${{ github.event.inputs.websocket || '1' }}